name: Add arXiv paper
description: 提交一个 arXiv 链接/ID 以请求入库
title: "[add-paper] "
labels:
  - add-paper
body:
  - type: input
    id: arxiv_input
    attributes:
      label: arXiv 链接或 ID
      description: 支持 abs/pdf/html 链接，或新 ID（如 2503.01078）
      placeholder: https://arxiv.org/abs/2503.01078
    validations:
      required: true
  - type: textarea
    id: note
    attributes:
      label: 备注
      description: 可选
      placeholder: 可补充你希望入库的原因
    validations:
      required: false
